### PR TITLE
move gitignore file to place where it should be

### PR DESCRIPTION
**Pull request by Rigorich**

### CODE REVIEW

**Comment by aperaverzeu** [comment]
good, I think we could merge it

**Comment by rosteeslove** [comment]
There can be multiple `.gitignore` files so there is no place "where it should be". But yeah, in our project having two gitignores is pointless.

**Comment by Rigorich** [comment]
> There can be multiple `.gitignore` files so there is no place "where it should be". But yeah, in our project having two gitignores is pointless.

There is some sense, btw. ClientApp is a separate project, so it have it's own gitignore.
This PR is about moving main gitignore file one folder up by tree, so .vs folder is no more a problem to git system

**Comment by rosteeslove** [comment]
> > There can be multiple `.gitignore` files so there is no place "where it should be". But yeah, in our project having two gitignores is pointless.
> 
> There is some sense, btw. ClientApp is a separate project, so it have it's own gitignore. This PR is about moving main gitignore file one folder up by tree, so .vs folder is no more a problem to git system

In this case, maybe keep the original `/.DS_Store` and `/.idea` entries in the root `.gitignore`?

**Review by rosteeslove — DISMISSED** [review]
On the other hand there is no need for `/.DS_Store` and `/.idea` ignored on all machines.

**Comment by Rigorich** [comment]
the fuck

**Comment by Rigorich** [comment]
we have 3 gitignores?!

**Comment by Rigorich** [comment]
@mrojaczy 
image

**Comment by rosteeslove** [comment]
nvmd, I confused the folders.

**Comment by rosteeslove** [comment]
All good, no complaints.

**Comment by Rigorich** [comment]
rider users
please check there is no trash files with current gitignores

**Review by rosteeslove — APPROVED** [review]
Ok, looks about right now.

**Comment by aperaverzeu** [comment]
@Rigorich @rasteeslove 
I think we need **/.DS_Store (for all mac users) and /.idea (for all rider enjoyers) in the root .gitignore

**Comment by rosteeslove** [comment]
> @Rigorich @rasteeslove I think we need **/.DS_Store (for all mac users) and /.idea (for all rider enjoyers) in the root .gitignore

That's fine too. I fact, redundancy of these files ignored on our computers is a better option that the need for all Mac/Rider users to add extra `.gitignore` entries.

**Review by rosteeslove — CHANGES_REQUESTED** [review]
Hence, I suggest keeping those entries.

**Review by rosteeslove — APPROVED** [review]
Yeah, I hope we are finally done.

**Comment by Rigorich** [comment]
> Yeah, I hope we are finally done.

image

**Review by aperaverzeu — APPROVED** [review]
God, please God no!

**Pull request merged**
